<?php
session_start();require __DIR__.'/config/database.php';require __DIR__.'/includes/functions.php';$pageTitle='Student Dashboard';
$success=$_SESSION['success']??'';$error=$_SESSION['error']??'';unset($_SESSION['success'],$_SESSION['error']);
$search=clean($_GET['search']??'');$branch=clean($_GET['branch']??'');$course=clean($_GET['course']??'');$status=clean($_GET['status']??'Active');$min=clean($_GET['min_cgpa']??'');$max=clean($_GET['max_cgpa']??'');
$where=[];$params=[];
if($search!==''){$where[]='(name LIKE :search OR email LIKE :search OR branch LIKE :search OR course LIKE :search)';$params[':search']='%'.$search.'%';}
if($branch!==''){$where[]='branch=:branch';$params[':branch']=$branch;}if($course!==''){$where[]='course=:course';$params[':course']=$course;}if($status!==''&&$status!=='All'){$where[]='status=:status';$params[':status']=$status;}if($min!==''&&is_numeric($min)){$where[]='cgpa>=:min';$params[':min']=(float)$min;}if($max!==''&&is_numeric($max)){$where[]='cgpa<=:max';$params[':max']=(float)$max;}
$sql='SELECT * FROM students'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY date_registered DESC,id DESC';$q=$pdo->prepare($sql);$q->execute($params);$students=$q->fetchAll();
$stats=$pdo->query("SELECT COUNT(*) total,COALESCE(AVG(cgpa),0) avgcgpa,SUM(status='Active') active,SUM(status='Inactive') inactive FROM students")->fetch();$branchStats=$pdo->query('SELECT branch,COUNT(*) total FROM students GROUP BY branch ORDER BY total DESC')->fetchAll();$highest=$pdo->query('SELECT MAX(cgpa) FROM students')->fetchColumn();include __DIR__.'/includes/header.php';?>
<main class="page-shell"><div class="container py-5">
<?php if($success):?><div class="alert alert-success alert-dismissible fade show"><?=e($success)?><button class="btn-close btn-close-white" data-bs-dismiss="alert"></button></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<section class="dashboard-heading mb-4"><div><span class="eyebrow">Student Dashboard</span><h1 class="mt-3">Manage every student from one place</h1><p>Full CRUD, search, filters, uploads, and live statistics.</p></div><a class="btn btn-primary btn-lg" href="add_student.php">Add Student</a></section>
<section class="stats-grid mb-4"><article class="stat-card"><i class="bi bi-people-fill"></i><span>Total Students</span><strong><?=(int)$stats['total']?></strong></article><article class="stat-card"><i class="bi bi-graph-up-arrow"></i><span>Average CGPA</span><strong><?=number_format((float)$stats['avgcgpa'],2)?></strong></article><article class="stat-card"><i class="bi bi-person-check-fill"></i><span>Active</span><strong><?=(int)$stats['active']?></strong></article><article class="stat-card"><i class="bi bi-person-dash-fill"></i><span>Inactive</span><strong><?=(int)$stats['inactive']?></strong></article></section>
<section class="glass-card branch-stats mb-4"><h2>Students per branch</h2><div class="branch-chip-list"><?php if(!$branchStats):?><span class="branch-chip">No data</span><?php else:foreach($branchStats as $b):?><span class="branch-chip"><?=e($b['branch'])?><strong><?=$b['total']?></strong></span><?php endforeach;endif;?></div></section>
<section class="glass-card filter-card mb-4"><form method="get"><div class="row g-3"><div class="col-lg-4"><label class="form-label">Search</label><input class="form-control" name="search" value="<?=e($search)?>" placeholder="Name, email, branch, course"></div><div class="col-md-6 col-lg-2"><label class="form-label">Branch</label><select class="form-select" name="branch"><option value="">All branches</option><?php foreach(branches() as $x):?><option value="<?=e($x)?>" <?=$branch===$x?'selected':''?>><?=e($x)?></option><?php endforeach;?></select></div><div class="col-md-6 col-lg-2"><label class="form-label">Course</label><select class="form-select" name="course"><option value="">All courses</option><?php foreach(courses() as $x):?><option value="<?=e($x)?>" <?=$course===$x?'selected':''?>><?=e($x)?></option><?php endforeach;?></select></div><div class="col-md-6 col-lg-2"><label class="form-label">Status</label><select class="form-select" name="status"><option <?=$status==='Active'?'selected':''?>>Active</option><option <?=$status==='Inactive'?'selected':''?>>Inactive</option><option <?=$status==='All'?'selected':''?>>All</option></select></div><div class="col-md-3 col-lg-1"><label class="form-label">Min</label><input class="form-control" type="number" name="min_cgpa" min="0" max="10" step=".01" value="<?=e($min)?>"></div><div class="col-md-3 col-lg-1"><label class="form-label">Max</label><input class="form-control" type="number" name="max_cgpa" min="0" max="10" step=".01" value="<?=e($max)?>"></div><div class="col-12"><button class="btn btn-primary">Apply Filters</button> <a class="btn btn-outline-light" href="index.php?status=All">Reset</a></div></div></form></section>
<section class="glass-card table-card"><h2>Student records <small class="record-count"><?=count($students)?> found</small></h2><?php if(!$students):?><div class="empty-state"><i class="bi bi-inbox"></i><h3>No students found</h3></div><?php else:?><div class="table-responsive"><table class="table table-dark table-hover student-table"><thead><tr><th>Photo</th><th>Student</th><th>Contact</th><th>Course</th><th>Branch</th><th>CGPA</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody><?php foreach($students as $s):$top=((float)$s['cgpa']===(float)$highest);?><tr class="<?=$top?'top-cgpa-row':''?>"><td><?php if($s['photo']):?><img class="table-photo" src="uploads/<?=e($s['photo'])?>"><?php else:?><div class="table-photo-placeholder"><?=e(initials($s['name']))?></div><?php endif;?></td><td><strong><?=e($s['name'])?></strong><small><?=e($s['college'])?></small></td><td><span><?=e($s['email'])?></span><small><?=e($s['phone'])?></small></td><td><?=e($s['course'])?></td><td><?=e($s['branch'])?></td><td><span class="cgpa-badge <?=$top?'top':''?>"><?=number_format((float)$s['cgpa'],2)?></span></td><td><span class="status-badge <?=strtolower($s['status'])?>"><?=e($s['status'])?></span></td><td><?=date('d M Y',strtotime($s['date_registered']))?></td><td><a class="btn btn-sm btn-outline-info" href="edit_student.php?id=<?=$s['id']?>"><i class="bi bi-pencil"></i></a> <a class="btn btn-sm btn-outline-danger delete-link" href="delete_student.php?id=<?=$s['id']?>"><i class="bi bi-trash"></i></a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
</div></main><?php include __DIR__.'/includes/footer.php';?>
