<?php
require __DIR__ . '/config/auth.php';
require __DIR__.'/config/database.php';
require __DIR__.'/includes/functions.php';
$pageTitle='Student Dashboard';
$success=$_SESSION['success']??'';$error=$_SESSION['error']??'';unset($_SESSION['success'],$_SESSION['error']);
$search=clean($_GET['search']??'');$branch=clean($_GET['branch']??'');$course=clean($_GET['course']??'');$status=clean($_GET['status']??'Active');$min=clean($_GET['min_cgpa']??'');$max=clean($_GET['max_cgpa']??'');
$where=[];$params=[];
if($search!==''){$where[]='(name LIKE :search OR email LIKE :search OR branch LIKE :search OR course LIKE :search)';$params[':search']='%'.$search.'%';}
if($branch!==''){$where[]='branch=:branch';$params[':branch']=$branch;}
if($course!==''){$where[]='course=:course';$params[':course']=$course;}
if($status!==''&&$status!=='All'){$where[]='status=:status';$params[':status']=$status;}
if($min!==''&&is_numeric($min)){$where[]='cgpa>=:min';$params[':min']=(float)$min;}
if($max!==''&&is_numeric($max)){$where[]='cgpa<=:max';$params[':max']=(float)$max;}
$sql='SELECT * FROM students'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY date_registered DESC,id DESC';
$q=$pdo->prepare($sql);$q->execute($params);$students=$q->fetchAll();
$stats=$pdo->query("SELECT COUNT(*) total,COALESCE(AVG(cgpa),0) avgcgpa,SUM(status='Active') active,SUM(status='Inactive') inactive FROM students")->fetch();
$branchStats=$pdo->query('SELECT branch,COUNT(*) total FROM students GROUP BY branch ORDER BY total DESC')->fetchAll();
$highest=$pdo->query('SELECT MAX(cgpa) FROM students')->fetchColumn();
$recent=$pdo->query('SELECT id,name,branch,course,photo,date_registered FROM students ORDER BY date_registered DESC,id DESC LIMIT 5')->fetchAll();
include __DIR__.'/includes/header.php';
?>
<main class="page-shell"><div class="container py-5 dashboard-fade">
<?php if($success):?><div class="alert alert-success alert-dismissible fade show"><i class="bi bi-check-circle-fill me-2"></i><?=e($success)?><button class="btn-close btn-close-white" data-bs-dismiss="alert"></button></div><?php endif;?>
<?php if($error):?><div class="alert alert-danger"><i class="bi bi-exclamation-triangle-fill me-2"></i><?=e($error)?></div><?php endif;?>
<section class="dashboard-heading mb-4"><div><span class="eyebrow"><i class="bi bi-speedometer2 me-1"></i>Student Dashboard</span><h1 class="mt-3">Manage every student from one place</h1><p>Full CRUD, secure login, uploads, search, filters, and live statistics.</p></div><a class="btn btn-primary btn-lg" href="add_student.php"><i class="bi bi-person-plus me-2"></i>Add Student</a></section>
<section class="stats-grid mb-4"><article class="stat-card"><i class="bi bi-people-fill"></i><span>Total Students</span><strong><?=(int)$stats['total']?></strong></article><article class="stat-card"><i class="bi bi-graph-up-arrow"></i><span>Average CGPA</span><strong><?=number_format((float)$stats['avgcgpa'],2)?></strong></article><article class="stat-card"><i class="bi bi-person-check-fill"></i><span>Active</span><strong><?=(int)$stats['active']?></strong></article><article class="stat-card"><i class="bi bi-person-dash-fill"></i><span>Inactive</span><strong><?=(int)$stats['inactive']?></strong></article></section>
<div class="row g-4 mb-4"><div class="col-lg-7"><section class="glass-card branch-stats h-100"><div class="section-row"><div><h2>Students per branch</h2><small>SQL aggregate overview</small></div><i class="bi bi-diagram-3 section-icon"></i></div><div class="branch-chip-list mt-3"><?php if(!$branchStats):?><span class="branch-chip">No data</span><?php else:foreach($branchStats as $b):?><span class="branch-chip"><?=e($b['branch'])?><strong><?=$b['total']?></strong></span><?php endforeach;endif;?></div></section></div><div class="col-lg-5"><section class="glass-card recent-card h-100"><div class="section-row"><div><h2>Recent registrations</h2><small>Latest five students</small></div><i class="bi bi-clock-history section-icon"></i></div><div class="recent-list"><?php if(!$recent):?><p class="text-secondary mb-0">No registrations yet.</p><?php else:foreach($recent as $r):?><a class="recent-item" href="view_student.php?id=<?=(int)$r['id']?>"><?php if($r['photo']):?><img src="uploads/<?=e($r['photo'])?>" alt="<?=e($r['name'])?>"><?php else:?><img src="assets/images/default-avatar.svg" alt="Default avatar"><?php endif;?><div><strong><?=e($r['name'])?></strong><small><?=e($r['course'])?> · <?=e($r['branch'])?></small></div><time><?=date('d M',strtotime($r['date_registered']))?></time></a><?php endforeach;endif;?></div></section></div></div>
<section class="glass-card filter-card mb-4"><form method="get"><div class="row g-3"><div class="col-lg-4"><label class="form-label">Search name, email, branch, or course</label><div class="input-group"><span class="input-group-text"><i class="bi bi-search"></i></span><input class="form-control" name="search" value="<?=e($search)?>" placeholder="Search students..."></div></div><div class="col-md-6 col-lg-2"><label class="form-label">Branch</label><select class="form-select" name="branch"><option value="">All branches</option><?php foreach(branches() as $x):?><option value="<?=e($x)?>" <?=$branch===$x?'selected':''?>><?=e($x)?></option><?php endforeach;?></select></div><div class="col-md-6 col-lg-2"><label class="form-label">Course</label><select class="form-select" name="course"><option value="">All courses</option><?php foreach(courses() as $x):?><option value="<?=e($x)?>" <?=$course===$x?'selected':''?>><?=e($x)?></option><?php endforeach;?></select></div><div class="col-md-6 col-lg-2"><label class="form-label">Status</label><select class="form-select" name="status"><option <?=$status==='Active'?'selected':''?>>Active</option><option <?=$status==='Inactive'?'selected':''?>>Inactive</option><option <?=$status==='All'?'selected':''?>>All</option></select></div><div class="col-md-3 col-lg-1"><label class="form-label">Min</label><input class="form-control" type="number" name="min_cgpa" min="0" max="10" step=".01" value="<?=e($min)?>"></div><div class="col-md-3 col-lg-1"><label class="form-label">Max</label><input class="form-control" type="number" name="max_cgpa" min="0" max="10" step=".01" value="<?=e($max)?>"></div><div class="col-12"><button class="btn btn-primary"><i class="bi bi-funnel-fill me-1"></i>Apply Filters</button> <a class="btn btn-outline-light" href="index.php?status=All"><i class="bi bi-arrow-counterclockwise me-1"></i>Reset</a></div></div></form></section>
<section class="glass-card table-card"><div class="table-title-row"><div><h2>Student records</h2><p class="mb-0"><?=count($students)?> result<?=count($students)===1?'':'s'?> found</p></div><i class="bi bi-table section-icon"></i></div><?php if(!$students):?><div class="empty-state"><i class="bi bi-search"></i><h3>No students found matching your search.</h3><p>Try another keyword or clear the filters.</p></div><?php else:?><div class="table-responsive mt-3"><table class="table table-dark table-striped table-hover student-table"><thead><tr><th>Photo</th><th>Student</th><th>Contact</th><th>Course</th><th>Branch</th><th>CGPA</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody><?php foreach($students as $s):$top=((float)$s['cgpa']===(float)$highest);?><tr class="<?=$top?'top-cgpa-row':''?>"><td><a href="view_student.php?id=<?=(int)$s['id']?>"><?php if($s['photo']):?><img class="table-photo" src="uploads/<?=e($s['photo'])?>" alt="<?=e($s['name'])?>"><?php else:?><img class="table-photo" src="assets/images/default-avatar.svg" alt="Default avatar"><?php endif;?></a></td><td><strong><?=highlightMatch($s['name'],$search)?></strong><small><?=e($s['college'])?></small></td><td><span><?=highlightMatch($s['email'],$search)?></span><small><?=e($s['phone'])?></small></td><td><?=highlightMatch($s['course'],$search)?></td><td><?=highlightMatch($s['branch'],$search)?></td><td><span class="cgpa-badge <?=$top?'top':''?>"><?=number_format((float)$s['cgpa'],2)?></span></td><td><span class="status-badge <?=strtolower($s['status'])?>"><?=e($s['status'])?></span></td><td><?=date('d M Y',strtotime($s['date_registered']))?></td><td><div class="action-buttons"><a class="btn btn-sm btn-outline-light" href="view_student.php?id=<?=(int)$s['id']?>" title="View"><i class="bi bi-eye"></i></a><a class="btn btn-sm btn-outline-info" href="edit_student.php?id=<?=(int)$s['id']?>" title="Edit"><i class="bi bi-pencil-square"></i></a><a class="btn btn-sm btn-outline-danger delete-link" href="delete_student.php?id=<?=(int)$s['id']?>" title="Delete"><i class="bi bi-trash"></i></a></div></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
</div></main><?php include __DIR__.'/includes/footer.php';?>
