<?php
require __DIR__ . '/config/auth.php';
require __DIR__.'/config/database.php';
require __DIR__.'/includes/functions.php';
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);if(!$id)redirect('index.php');
$q=$pdo->prepare('SELECT * FROM students WHERE id=?');$q->execute([$id]);$student=$q->fetch();
if(!$student){$_SESSION['error']='Student not found.';redirect('index.php');}
$pageTitle='Student Profile';include __DIR__.'/includes/header.php';
?>
<main class="page-shell"><div class="container py-5 dashboard-fade"><section class="glass-card student-profile-card mx-auto"><div class="profile-hero"><div class="profile-photo-shell"><?php if($student['photo']):?><img src="uploads/<?=e($student['photo'])?>" alt="<?=e($student['name'])?>"><?php else:?><img src="assets/images/default-avatar.svg" alt="Default avatar"><?php endif;?></div><div><span class="status-badge <?=strtolower($student['status'])?>"><?=e($student['status'])?></span><h1><?=e($student['name'])?></h1><p><?=e($student['course'])?> · <?=e($student['branch'])?></p></div></div><div class="profile-detail-grid"><article><i class="bi bi-envelope"></i><small>Email</small><strong><?=e($student['email'])?></strong></article><article><i class="bi bi-telephone"></i><small>Phone</small><strong><?=e($student['phone'])?></strong></article><article><i class="bi bi-graph-up-arrow"></i><small>CGPA</small><strong><?=number_format((float)$student['cgpa'],2)?></strong></article><article><i class="bi bi-building"></i><small>College</small><strong><?=e($student['college'])?></strong></article><article class="full"><i class="bi bi-geo-alt"></i><small>Address</small><strong><?=nl2br(e($student['address']))?></strong></article><article class="full"><i class="bi bi-calendar-check"></i><small>Registered</small><strong><?=date('d F Y, h:i A',strtotime($student['date_registered']))?></strong></article></div><div class="d-grid d-sm-flex gap-3 mt-4"><a class="btn btn-primary flex-grow-1" href="edit_student.php?id=<?=(int)$student['id']?>"><i class="bi bi-pencil-square me-2"></i>Edit Student</a><a class="btn btn-outline-light" href="index.php?status=All"><i class="bi bi-arrow-left me-2"></i>Back</a></div></section></div></main><?php include __DIR__.'/includes/footer.php';?>
