USE student_management;
ALTER TABLE students
 ADD COLUMN IF NOT EXISTS course VARCHAR(100) NOT NULL AFTER branch,
 ADD COLUMN IF NOT EXISTS address TEXT NOT NULL AFTER college,
 ADD COLUMN IF NOT EXISTS photo VARCHAR(255) DEFAULT NULL AFTER address,
 ADD COLUMN IF NOT EXISTS status ENUM('Active','Inactive') NOT NULL DEFAULT 'Active' AFTER photo,
 ADD COLUMN IF NOT EXISTS date_registered TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER status;
